# Generated by Django 2.1.8 on 2019-05-15 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190515_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_set', to='movies.Movie'),
        ),
    ]
