# Generated by Django 2.1.8 on 2019-05-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190515_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='avgScore',
            field=models.FloatField(default=0.0),
        ),
    ]
